language: node_js
node_js:
  - stable

cache:
  directories:
    - "node_modules"

install:
  - cd webpack4-mobx-simple-page
  - npm install
  - npm run build

script:
  - chmod u+x deploy.sh
  - bash ./deploy.sh
